# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tidy_html_int <- function(source, options, show_errors) {
    .Call('htmltidy_tidy_html_int', PACKAGE = 'htmltidy', source, options, show_errors)
}

